### ISSUE TITLE
Logic Error in ValueComparator.

### ISSUE THREAD

**Issue by taveratch** [OOP2018/coinpurse-neung123#6]
https://github.com/OOP2018/coinpurse-neung123/blob/f85289bd33fa217e2aa66f772a231529613a9333/src/coinpurse/ValueComparator.java#L25-L31

It should be an alphabetical comparison, not length comparison.

**Comment by taveratch** [comment]
It's still not fixed

**Comment by neung123** [comment]
ขออนุญาตภาษาไทยนะคะ ไม่รู้จะเขียนยังไงดี

หนูเพิ่ง push ขึ้นไปตอนจบคาบนะคะพี่แต่ดูเหมือนว่ามันจะไม่ขึ้น 
addเข้าไปใหม่มันก็แจ้งว่าไฟล์ไม่มีการเปลี่ยนแปลงทั้งๆที่ทำหมดแล้ว
มีวิธีอื่นนอกจะcloneแล้วcopyแปะใหม่ไหมคะ
